"""Test

Revision ID: 1bd81315f221
Revises: 7fe2a76697f1
Create Date: 2021-02-02 20:37:10.055693

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1bd81315f221'
down_revision = '7fe2a76697f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
