"""Re-length column String into pockemon tables

Revision ID: 479879a24b01
Revises: 52ff9e949f46
Create Date: 2021-02-16 13:26:07.599224

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '479879a24b01'
down_revision = '52ff9e949f46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pockemon', 'name',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=30),
               existing_nullable=True)
    op.alter_column('pockemon', 'url',
               existing_type=sa.VARCHAR(length=1),
               type_=sa.String(length=50),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pockemon', 'url',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=1),
               existing_nullable=True)
    op.alter_column('pockemon', 'name',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)
    # ### end Alembic commands ###
