"""Re-length column String into pockemon tables

Revision ID: 52ff9e949f46
Revises: 9e8584c0664a
Create Date: 2021-02-16 13:20:36.108275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52ff9e949f46'
down_revision = '9e8584c0664a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
