"""Re-length column String into pockemon tables

Revision ID: e57223ab6d20
Revises: 1828247ea0c4
Create Date: 2021-02-16 13:16:26.908560

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e57223ab6d20'
down_revision = '1828247ea0c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
