"""Re-length column String into pockemon tables

Revision ID: 9e8584c0664a
Revises: e57223ab6d20
Create Date: 2021-02-16 13:19:47.213248

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e8584c0664a'
down_revision = 'e57223ab6d20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
