"""Added to UserPockemon column created

Revision ID: ba810ee6d290
Revises: 479879a24b01
Create Date: 2021-02-24 14:00:46.449067

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba810ee6d290'
down_revision = '479879a24b01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_pockemon', sa.Column('createdAt', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_pockemon', 'createdAt')
    # ### end Alembic commands ###
